package com.dsp.equipment.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table equipment
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Equipment  {
    /**
     * Database Column Remarks:
     *   设备id
     */
    private String eqId;

    /**
     * Database Column Remarks:
     *   所属分类
     */
    private String sortName;
    private String sortName1;

    /**
     * Database Column Remarks:
     *   设备名称
     */
    private String eqName;

    /**
     * Database Column Remarks:
     *   型号
     */
    private String model;

    /**
     * Database Column Remarks:
     *   单价
     */
    private Double unitPrice;

    /**
     * Database Column Remarks:
     *   产地
     */
    private String placeOfOrigin;

    /**
     * Database Column Remarks:
     *   供应商
     */
    private String supName;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   是否过期（0正常 1过期 ）
     */
    private Integer isEnd;

    /**
     * Database Column Remarks:
     *   是否损坏（0正常 1损坏 ）
     */
    private Integer isOk;

    /**
     * Database Column Remarks:
     *   备注
     */
    private String remakes;
    private String isTime;
    private String isUser;
    private String isRes;
    private String isType;

    public String getIsType() {
        return isType;
    }

    public void setIsType(String isType) {
        this.isType = isType;
    }

    public String getIsTime() {
        return isTime;
    }

    public void setIsTime(String isTime) {
        this.isTime = isTime;
    }

    public String getIsUser() {
        return isUser;
    }

    public void setIsUser(String isUser) {
        this.isUser = isUser;
    }

    public String getIsRes() {
        return isRes;
    }

    public void setIsRes(String isRes) {
        this.isRes = isRes;
    }

    public String getSortName1() {
        return sortName1;
    }

    public void setSortName1(String sortName1) {
        this.sortName1 = sortName1;
    }

    public String getEqId() {
        return eqId;
    }

    public void setEqId(String eqId) {
        this.eqId = eqId;
    }

    public String getSortName() {
        return sortName;
    }

    public void setSortName(String sortName) {
        this.sortName = sortName == null ? null : sortName.trim();
    }

    public String getEqName() {
        return eqName;
    }

    public void setEqName(String eqName) {
        this.eqName = eqName == null ? null : eqName.trim();
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public String getPlaceOfOrigin() {
        return placeOfOrigin;
    }

    public void setPlaceOfOrigin(String placeOfOrigin) {
        this.placeOfOrigin = placeOfOrigin == null ? null : placeOfOrigin.trim();
    }

    public String getSupName() {
        return supName;
    }

    public void setSupName(String supName) {
        this.supName = supName == null ? null : supName.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getIsEnd() {
        return isEnd;
    }

    public void setIsEnd(Integer isEnd) {
        this.isEnd = isEnd;
    }

    public Integer getIsOk() {
        return isOk;
    }

    public void setIsOk(Integer isOk) {
        this.isOk = isOk;
    }

    public String getRemakes() {
        return remakes;
    }

    public void setRemakes(String remakes) {
        this.remakes = remakes == null ? null : remakes.trim();
    }
}