package com.dsp.equipment.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table purchase
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Purchase {
    /**
     * Database Column Remarks:
     *   订单编号
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   订单日期
     */
    private String orderTime;

    /**
     * Database Column Remarks:
     *   项目名称
     */
    private String orderProject;

    /**
     * Database Column Remarks:
     *   供应商编号
     */
    private String supId;
    private String supName;

    /**
     * Database Column Remarks:
     *   采购员编号
     */
    private String userId;
    private String userName;

    /**
     * Database Column Remarks:
     *   设备编号
     */
    private String eqId;
    private String eqName;

    /**
     * Database Column Remarks:
     *   订购数量
     */
    private Integer orderNum;

    /**
     * Database Column Remarks:
     *   预算
     */
    private Double budget;

    /**
     * Database Column Remarks:
     *   订单说明
     */
    private String explainInfo;

    /**
     * Database Column Remarks:
     *   订单状态
     */
    private String status;

    /**
     * Database Column Remarks:
     *   订单图片
     */
    private String photo;

    /**
     * Database Column Remarks:
     *   订单审核(0审核通过 1审核失败 2未审核)
     */
    private Integer examine;

    public String getSupName() {
        return supName;
    }

    public void setSupName(String supName) {
        this.supName = supName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEqName() {
        return eqName;
    }

    public void setEqName(String eqName) {
        this.eqName = eqName;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    public String getOrderTime() {
        return orderTime;
    }

    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime;
    }

    public String getOrderProject() {
        return orderProject;
    }

    public void setOrderProject(String orderProject) {
        this.orderProject = orderProject == null ? null : orderProject.trim();
    }

    public String getSupId() {
        return supId;
    }

    public void setSupId(String supId) {
        this.supId = supId == null ? null : supId.trim();
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    public String getEqId() {
        return eqId;
    }

    public void setEqId(String eqId) {
        this.eqId = eqId == null ? null : eqId.trim();
    }

    public Integer getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public Double getBudget() {
        return budget;
    }

    public void setBudget(Double budget) {
        this.budget = budget;
    }

    public String getexplainInfo() {
        return explainInfo;
    }

    public void setexplainInfo(String explainInfo) {
        this.explainInfo = explainInfo == null ? null : explainInfo.trim();
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    public Integer getExamine() {
        return examine;
    }

    public void setExamine(Integer examine) {
        this.examine = examine;
    }
}