package com.dsp.equipment.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sort
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Sort {
    /**
     * Database Column Remarks:
     *   分类id
     */
    private String sortId;

    /**
     * Database Column Remarks:
     *   分类名称
     */
    private String sortName;

    /**
     * Database Column Remarks:
     *   分类描述
     */
    private String describeInfo;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    private String createTime;

    public String getSortId() {
        return sortId;
    }

    public void setSortId(String sortId) {
        this.sortId = sortId;
    }

    public String getSortName() {
        return sortName;
    }

    public void setSortName(String sortName) {
        this.sortName = sortName == null ? null : sortName.trim();
    }

    public String getDescribeInfo() {
        return describeInfo;
    }

    public void setDescribeInfo(String describeInfo) {
        this.describeInfo = describeInfo;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
}