package com.dsp.equipment.entity;


/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table supplier
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Supplier {
    /**
     * Database Column Remarks:
     *   供应商id
     */
    private String supId;

    /**
     * Database Column Remarks:
     *   供应商名称
     */
    private String supName;

    /**
     * Database Column Remarks:
     *   产品信息
     */
    private String product;

    /**
     * Database Column Remarks:
     *   联系人
     */
    private String contacts;

    /**
     * Database Column Remarks:
     *   联系人电话
     */
    private String contactPhone;

    /**
     * Database Column Remarks:
     *   联系地址
     */
    private String address;

    /**
     * Database Column Remarks:
     *   备注
     */
    private String remakes;

    public String getSupId() {
        return supId;
    }

    public void setSupId(String supId) {
        this.supId = supId;
    }

    public String getSupName() {
        return supName;
    }

    public void setSupName(String supName) {
        this.supName = supName == null ? null : supName.trim();
    }

    public String getProduct() {
        return product;
    }

    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    public String getContacts() {
        return contacts;
    }

    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    public String getContactPhone() {
        return contactPhone;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    public String getRemakes() {
        return remakes;
    }

    public void setRemakes(String remakes) {
        this.remakes = remakes == null ? null : remakes.trim();
    }
}