package com.dsp.equipment.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table warehousing
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Warehousing  {
    /**
     * Database Column Remarks:
     *   订单编号
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   入库时间
     */
    private Date wareTime;

    /**
     * Database Column Remarks:
     *   入库人
     */
    private String warePerson;
    private String warePerson1;
    private String type;

    public String getWarePerson1() {
        return warePerson1;
    }

    public void setWarePerson1(String warePerson1) {
        this.warePerson1 = warePerson1;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    public Date getWareTime() {
        return wareTime;
    }

    public void setWareTime(Date wareTime) {
        this.wareTime = wareTime;
    }

    public String getWarePerson() {
        return warePerson;
    }

    public void setWarePerson(String warePerson) {
        this.warePerson = warePerson == null ? null : warePerson.trim();
    }
}